version: '3.7'
services:
#Nginx service
  contacapp-nginx:
    build:
      context: ./
    image: conctacapp-nginx
    volumes:
      # - type: bind
      #   source: ./
      #   target: /apps
      - type: bind
        source: ./nginx/config
        target: /etc/nginx/conf.d
      - type: bind
        source: ./nginx/ssl
        target: /etc/ssl
    container_name: contacapp-nginx
    ports:
      - "80:80"
      - "443:443"